wip

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -37,13 +37,22 @@ jobs:
           export SKIP_FLAGS_NON_UNIT_TESTS="-Dcheckstyle.skip -Dpmd.skip -Dcpd.skip -Dfindbugs.skip -Dspotbugs.skip"
           echo "SKIP_FLAGS_NON_UNIT_TESTS=$SKIP_FLAGS_NON_UNIT_TESTS" >> $GITHUB_ENV
           echo "SKIP_FLAGS_ALL_TESTS=$SKIP_FLAGS_NON_UNIT_TESTS -Dmaven.test.skip=true" >> $GITHUB_ENV
+          if [ $GITHUB_EVENT_NAME != "pull_request" && $GITHUB_REF_NAME="add_whitesource" ]
+          then
+            export MAN_BRANCH_BUILD=true
+          else
+            export MAN_BRANCH_BUILD=false
+          fi
+          echo "$MAN_BRANCH_BUILD"
+          echo "MAN_BRANCH_BUILD=$MAN_BRANCH_BUILD" >> $GITHUB_ENV
+       - run: echo "$MAN_BRANCH_BUILD"
 #      - name: Static Code Analysis
 #        run: mvn -B compile -Pmaas-static-code-analysis --file service/pom.xml
 #      - name: Unit Tests
 #        run: mvn -B test $SKIP_FLAGS_NON_UNIT_TESTS --file service/pom.xml
-      - name: Generate Artifacts
-        run: |
-          mvn install $SKIP_FLAGS_ALL_TESTS --file service/pom.xml
+#      - name: Generate Artifacts
+#        run: |
+#          mvn install $SKIP_FLAGS_ALL_TESTS --file service/pom.xml
 #      - name: Sonar Scan
 #        env:
 #          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -52,34 +61,34 @@ jobs:
 #          mvn -B $SKIP_FLAGS_ALL_TESTS \
 #            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=SolaceLabs_runtime-agent \
 #            --file service/pom.xml
-      - name: Download latest Mend/Whitesource Agent
-        if: ${{ github.ref == 'refs/heads/add_whitesource' }}
-        env:
-          unified_agent_url: "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar"
-          unified_agent_sha_url: "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar.sha256"
-        run: |
-          curl -LJOs ${{ env.unified_agent_url }}
-          sha_from_jar=$(sha256sum  wss-unified-agent.jar | awk '{print $1}')
-          curl -LJOs ${{ env.unified_agent_sha_url }}
-          sha_from_file=$(cat wss-unified-agent.jar.sha256 | awk '{print $1}')
-          echo "sha_from_jar: $sha_from_jar"
-          echo "sha_from_file: $sha_from_file"
-          if [[ "$sha_from_file" == "$sha_from_jar" ]]; then
-              echo "Integrity of the wss-unified-agent.jar file verified .."
-          else
-              echo "Integrity check of wss-unified-agent.jar file failed .."
-              exit 1
-          fi
-      - name: Copy Maven Dependencies
-        run: mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=target/lib --file service/pom.xml
-      - name: Whitesource Scan
+#      - name: Download latest Mend/Whitesource Agent
 #        if: ${{ github.ref == 'refs/heads/add_whitesource' }}
-        env:
-          WS_APIKEY: ${{ secrets.WHITESOURCE_API_KEY }}
-          WS_PROJECTTOKEN: ${{ secrets.WHITESOURCE_PROJECT_TOKEN }}
-          TARGET_DIR: "service/application/target/lib"
-          WS_EXCLUDES: "local-storage-plugin*.jar,plugin*.jar,kafka-plugin*.jar,confluent-schema-registry-plugin*.jar"
-        run: java -jar wss-unified-agent.jar -d  ${{ env.TARGET_DIR }}  -logLevel Info
+#        env:
+#          unified_agent_url: "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar"
+#          unified_agent_sha_url: "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar.sha256"
+#        run: |
+#          curl -LJOs ${{ env.unified_agent_url }}
+#          sha_from_jar=$(sha256sum  wss-unified-agent.jar | awk '{print $1}')
+#          curl -LJOs ${{ env.unified_agent_sha_url }}
+#          sha_from_file=$(cat wss-unified-agent.jar.sha256 | awk '{print $1}')
+#          echo "sha_from_jar: $sha_from_jar"
+#          echo "sha_from_file: $sha_from_file"
+#          if [[ "$sha_from_file" == "$sha_from_jar" ]]; then
+#              echo "Integrity of the wss-unified-agent.jar file verified .."
+#          else
+#              echo "Integrity check of wss-unified-agent.jar file failed .."
+#              exit 1
+#          fi
+#      - name: Copy Maven Dependencies
+#        run: mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=target/lib --file service/pom.xml
+#      - name: Whitesource Scan
+##        if: ${{ github.ref == 'refs/heads/add_whitesource' }}
+#        env:
+#          WS_APIKEY: ${{ secrets.WHITESOURCE_API_KEY }}
+#          WS_PROJECTTOKEN: ${{ secrets.WHITESOURCE_PROJECT_TOKEN }}
+#          TARGET_DIR: "service/application/target/lib"
+#          WS_EXCLUDES: "local-storage-plugin*.jar,plugin*.jar,kafka-plugin*.jar,confluent-schema-registry-plugin*.jar"
+#        run: java -jar wss-unified-agent.jar -d  ${{ env.TARGET_DIR }}  -logLevel Info
 
 #      - name: Deploy Artifacts
 #        if: ${{ github.ref == 'refs/heads/main' }}
