add a switch for whitesource scan

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -37,15 +37,13 @@ jobs:
           export SKIP_FLAGS_NON_UNIT_TESTS="-Dcheckstyle.skip -Dpmd.skip -Dcpd.skip -Dfindbugs.skip -Dspotbugs.skip"
           echo "SKIP_FLAGS_NON_UNIT_TESTS=$SKIP_FLAGS_NON_UNIT_TESTS" >> $GITHUB_ENV
           echo "SKIP_FLAGS_ALL_TESTS=$SKIP_FLAGS_NON_UNIT_TESTS -Dmaven.test.skip=true" >> $GITHUB_ENV
-          echo "$GITHUB_EVENT_NAME"
-          echo "$GITHUB_REF_NAME"
           if [[ $GITHUB_EVENT_NAME != "pull_request" && $GITHUB_REF_NAME="add_whitesource" ]]; then
-            export MAIN_BRANCH_BUILD=true
+            export WHITESOURCE_SCAN=true
           else
-            export MAIN_BRANCH_BUILD=false
+            export WHITESOURCE_SCAN=false
           fi
-          echo "$MAIN_BRANCH_BUILD"
-          echo "MAIN_BRANCH_BUILD=$MAIN_BRANCH_BUILD" >> $GITHUB_ENV
+          echo "$WHITESOURCE_SCAN"
+          echo "WHITESOURCE_SCAN=$WHITESOURCE_SCAN" >> $GITHUB_ENV
       - run: echo "$MAIN_BRANCH_BUILD"
       - name: test
         if: env.MAIN_BRANCH_BUILD=='true'
@@ -65,34 +63,35 @@ jobs:
 #          mvn -B $SKIP_FLAGS_ALL_TESTS \
 #            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=SolaceLabs_runtime-agent \
 #            --file service/pom.xml
-#      - name: Download latest Mend/Whitesource Agent
-#        if: ${{ github.ref == 'refs/heads/add_whitesource' }}
-#        env:
-#          unified_agent_url: "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar"
-#          unified_agent_sha_url: "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar.sha256"
-#        run: |
-#          curl -LJOs ${{ env.unified_agent_url }}
-#          sha_from_jar=$(sha256sum  wss-unified-agent.jar | awk '{print $1}')
-#          curl -LJOs ${{ env.unified_agent_sha_url }}
-#          sha_from_file=$(cat wss-unified-agent.jar.sha256 | awk '{print $1}')
-#          echo "sha_from_jar: $sha_from_jar"
-#          echo "sha_from_file: $sha_from_file"
-#          if [[ "$sha_from_file" == "$sha_from_jar" ]]; then
-#              echo "Integrity of the wss-unified-agent.jar file verified .."
-#          else
-#              echo "Integrity check of wss-unified-agent.jar file failed .."
-#              exit 1
-#          fi
-#      - name: Copy Maven Dependencies
-#        run: mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=target/lib --file service/pom.xml
-#      - name: Whitesource Scan
-##        if: ${{ github.ref == 'refs/heads/add_whitesource' }}
-#        env:
-#          WS_APIKEY: ${{ secrets.WHITESOURCE_API_KEY }}
-#          WS_PROJECTTOKEN: ${{ secrets.WHITESOURCE_PROJECT_TOKEN }}
-#          TARGET_DIR: "service/application/target/lib"
-#          WS_EXCLUDES: "local-storage-plugin*.jar,plugin*.jar,kafka-plugin*.jar,confluent-schema-registry-plugin*.jar"
-#        run: java -jar wss-unified-agent.jar -d  ${{ env.TARGET_DIR }}  -logLevel Info
+      - name: Download latest Mend/Whitesource Agent
+        if: env.WHITESOURCE_SCAN=='true'
+        env:
+          unified_agent_url: "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar"
+          unified_agent_sha_url: "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar.sha256"
+        run: |
+          curl -LJOs ${{ env.unified_agent_url }}
+          sha_from_jar=$(sha256sum  wss-unified-agent.jar | awk '{print $1}')
+          curl -LJOs ${{ env.unified_agent_sha_url }}
+          sha_from_file=$(cat wss-unified-agent.jar.sha256 | awk '{print $1}')
+          echo "sha_from_jar: $sha_from_jar"
+          echo "sha_from_file: $sha_from_file"
+          if [[ "$sha_from_file" == "$sha_from_jar" ]]; then
+              echo "Integrity of the wss-unified-agent.jar file verified .."
+          else
+              echo "Integrity check of wss-unified-agent.jar file failed .."
+              exit 1
+          fi
+      - name: Copy Maven Dependencies
+        if: env.WHITESOURCE_SCAN=='true'
+        run: mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=target/lib --file service/pom.xml
+      - name: Whitesource Scan
+        if: env.WHITESOURCE_SCAN=='true'
+        env:
+          WS_APIKEY: ${{ secrets.WHITESOURCE_API_KEY }}
+          WS_PROJECTTOKEN: ${{ secrets.WHITESOURCE_PROJECT_TOKEN }}
+          TARGET_DIR: "service/application/target/lib"
+          WS_EXCLUDES: "local-storage-plugin*.jar,plugin*.jar,kafka-plugin*.jar,confluent-schema-registry-plugin*.jar"
+        run: java -jar wss-unified-agent.jar -d  ${{ env.TARGET_DIR }}  -logLevel Info
 
 #      - name: Deploy Artifacts
 #        if: ${{ github.ref == 'refs/heads/main' }}
